create table us_role (us_role_id bigint generated by default as identity,
active boolean not null,
created_by bigint,
created_on timestamp,
updated_by bigint,
updated_on timestamp,
role_name varchar(255) not null,
primary key (us_role_id));

create table us_user (us_user_id bigint generated by default as identity,
active boolean not null,
created_by bigint,
created_on timestamp,
updated_by bigint,
updated_on timestamp,
email varchar(255) not null,
password varchar(255) not null,
user_name varchar(255) not null,
primary key (us_user_id));

create table us_users_roles (us_user_id bigint not null,
us_role_id bigint not null);

alter table us_role add constraint uk_role_name unique (role_name);
alter table us_user add constraint uk_user_email unique (email);
alter table us_user add constraint uk_user_name unique (user_name);
alter table us_users_roles add constraint fk_us_role_id foreign key (us_role_id) references us_role;
alter table us_users_roles add constraint fk_us_user_id foreign key (us_user_id) references us_user;